version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hotel_booking_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1zJMa1Taswtr6o2
      POSTGRES_DB: hotel_booking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
