openapi: 3.0.0
info:
  title: Hotel Booking API
  version: 1.0.0

tags:
  - name: bookings
    description: Operations about hotel bookings

paths:
  /bookings:
    get:
      tags:
        - bookings
      summary: Get a list of bookings
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                [{"booking_id": "uuid-1", "user_id": "uuid-user-1", "hotel_id": "uuid-hotel-1", "checkin_date": "2023-01-01", "checkout_date": "2023-01-05", "status": "CONFIRMED"}, {"booking_id": "uuid-2", "user_id": "uuid-user-2", "hotel_id": "uuid-hotel-2", "checkin_date": "2023-02-01", "checkout_date": "2023-02-05", "status": "PENDING"}]
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'

    post:
      tags:
        - bookings
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
      responses:
        '201':
          description: Booking created successfully
          content:
            application/json:
              example: {"booking_id": "uuid-3", "user_id": "uuid-user-3", "hotel_id": "uuid-hotel-3", "checkin_date": "2023-03-01", "checkout_date": "2023-03-05", "status": "pending"}

  /bookings/{booking_id}:
    get:
      tags:
        - bookings
      summary: Get details of a specific booking
      parameters:
        - name: booking_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                {"booking_id": "uuid-1", "user_id": "uuid-user-1", "hotel_id": "uuid-hotel-1", "checkin_date": "2023-01-01", "checkout_date": "2023-01-05", "status": "CONFIRMED"}
              schema:
                $ref: '#/components/schemas/Booking'

    put:
      tags:
        - bookings
      summary: Update details of a booking
      parameters:
        - name: booking_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBookingRequest'
      responses:
        '200':
          description: Booking updated successfully
          content:
            application/json:
              example: {"booking_id": "uuid-1", "user_id": "uuid-user-1", "hotel_id": "uuid-hotel-1", "checkin_date": "2023-01-01", "checkout_date": "2023-01-10", "status": "confirmed"}

    delete:
      tags:
        - bookings
      summary: Cancel a booking
      parameters:
        - name: booking_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Booking canceled successfully

components:
  schemas:
    Booking:
      type: object
      properties:
        booking_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        hotel_id:
          type: string
          format: uuid
        checkin_date:
          type: string
          format: date
        checkout_date:
          type: string
          format: date
        status:
          type: string
          enum:
            - PENDING
            - CANCELLED_BY_CUSTOMER
            - CANCELLED_BY_HOTEL
            - DECLINED
            - CONFIRMED
            - NO_SHOW
            - COMPLETED
    
    CreateBookingRequest:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        hotel_id:
          type: string
          format: uuid
        checkin_date:
          type: string
          format: date
        checkout_date:
          type: string
          format: date
        status:
          type: string
          enum:
            - PENDING
            - CANCELLED_BY_CUSTOMER
            - CANCELLED_BY_HOTEL
            - DECLINED
            - CONFIRMED
            - NO_SHOW
            - COMPLETED

    UpdateBookingRequest:
      type: object
      properties:
        booking_id:
          type: string
          format: uuid
        checkin_date:
          type: string
          format: date
        checkout_date:
          type: string
          format: date
        status:
          type: string
          enum:
            - PENDING
            - CANCELLED_BY_CUSTOMER
            - CANCELLED_BY_HOTEL
            - DECLINED
            - CONFIRMED
            - NO_SHOW
            - COMPLETED
